import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Providers } from "@/components/providers/providers";

const inter = Inter({ 
  subsets: ["latin"],
  variable: '--font-sans'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <html lang="en" className="dTheme"  suppressHydrationWarning>
      <body className={cn("min-h-screen bg-background text-foreground antialiased font-sans", inter.variable)}>
        <Providers>
          {children}
        </Providers>
        
        </body>
    </html>
  </>
  );
}
